apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw2.fullname" . }}
  namespace: {{ .Values.hw_namespace }}
  labels:
    {{- include "hw2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: http
  selector:
    {{- include "hw2.selectorLabels" . | nindent 4 }}
